In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [36]:
from google.colab import files
uploaded = files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads (1).csv


In [37]:
import io
Ads = pd.read_csv(io.BytesIO(uploaded['Social_Network_Ads.csv']))

In [38]:
# Ads = Ads.dropna()
# Ads.isnull().sum()

In [39]:
X = Ads[["Age","EstimatedSalary"]]
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [40]:
# from sklearn.impute import SimpleImputer
# imp = SimpleImputer()
# X = imp.fit_transform(X)
# X = pd.DataFrame(X, columns=['Age', 'EstimatedSalary'])
# X.isnull().sum()

In [41]:
Y = Ads["Purchased"]

In [42]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [43]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(model.score(X_test,y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

0.65


array([[52,  0],
       [28,  0]])

In [44]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

# from sklearn.tree import DecisionTreeClassifier

# model = DecisionTreeClassifier()
# model.fit(X_train,y_train)
# pred = model.predict(X_test)
# print(model.score(X_test,y_test))
# from sklearn.metrics import confusion_matrix
# confusion_matrix(y_test, pred)

In [45]:
# from sklearn.ensemble import RandomForestClassifier

# model = RandomForestClassifier()
# model.fit(X_train,y_train)
# pred = model.predict(X_test)
# print(model.score(X_test,y_test))
# from sklearn.metrics import confusion_matrix
# confusion_matrix(y_test, pred)

In [46]:
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
X = Ads[["Gender","Age","EstimatedSalary"]]

# from sklearn.impute import SimpleImputer
# imp = SimpleImputer(strategy="most_frequent")
# X = imp.fit_transform(X)
# # print(X)
# X = pd.DataFrame(X)
# X
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
# Xa = X.copy()
X["Gender"] = encoder.fit_transform(X[["Gender"]])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':


In [48]:
# X.isnull().sum()
X

Gender  Age  EstimatedSalary
0       1.0   19            19000
1       1.0   35            20000
2       0.0   26            43000
3       0.0   27            57000
4       1.0   19            76000
..      ...  ...              ...
395     0.0   46            41000
396     1.0   51            23000
397     0.0   50            20000
398     1.0   36            33000
399     0.0   49            36000

[400 rows x 3 columns]

In [49]:
from sklearn.preprocessing import MinMaxScaler
Scaler = MinMaxScaler(feature_range = (0,1))
X = Scaler.fit_transform(X)

In [50]:
X

array([[1.        , 0.02380952, 0.02962963],
       [1.        , 0.4047619 , 0.03703704],
       [0.        , 0.19047619, 0.20740741],
       ...,
       [0.        , 0.76190476, 0.03703704],
       [1.        , 0.42857143, 0.13333333],
       [0.        , 0.73809524, 0.15555556]])

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(model.score(X_test,y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

0.875


array([[51,  1],
       [ 9, 19]])

In [52]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

# from sklearn.tree import DecisionTreeClassifier


# model = DecisionTreeClassifier()
# model.fit(X_train,y_train)
# pred = model.predict(X_test)
# print(model.score(X_test,y_test))
# from sklearn.metrics import confusion_matrix
# confusion_matrix(y_test, pred)


In [53]:
# from sklearn.ensemble import RandomForestClassifier

# model = RandomForestClassifier()
# model.fit(X_train,y_train)
# pred = model.predict(X_test)
# print(model.score(X_test,y_test))
# from sklearn.metrics import confusion_matrix
# confusion_matrix(y_test, pred)

In [54]:
from sklearn.preprocessing import OneHotEncoder
X = Ads[["Gender","Age","EstimatedSalary"]]
# creating instance of one-hot-encoder
encoder = OneHotEncoder(handle_unknown='ignore')

encoder_data = pd.DataFrame(encoder.fit_transform(Ads[['Gender']]).toarray())
# merge with main df bridge_df on key values
X = X.join(encoder_data)

In [55]:
X

Gender  Age  EstimatedSalary    0    1
0      Male   19            19000  0.0  1.0
1      Male   35            20000  0.0  1.0
2    Female   26            43000  1.0  0.0
3    Female   27            57000  1.0  0.0
4      Male   19            76000  0.0  1.0
..      ...  ...              ...  ...  ...
395  Female   46            41000  1.0  0.0
396    Male   51            23000  0.0  1.0
397  Female   50            20000  1.0  0.0
398    Male   36            33000  0.0  1.0
399  Female   49            36000  1.0  0.0

[400 rows x 5 columns]

In [56]:
X = X[["Age","EstimatedSalary",0,1]]

In [57]:
X

Age  EstimatedSalary    0    1
0     19            19000  0.0  1.0
1     35            20000  0.0  1.0
2     26            43000  1.0  0.0
3     27            57000  1.0  0.0
4     19            76000  0.0  1.0
..   ...              ...  ...  ...
395   46            41000  1.0  0.0
396   51            23000  0.0  1.0
397   50            20000  1.0  0.0
398   36            33000  0.0  1.0
399   49            36000  1.0  0.0

[400 rows x 4 columns]

In [58]:
from sklearn.preprocessing import MinMaxScaler
Scaler = MinMaxScaler(feature_range = (0,1))
X = Scaler.fit_transform(X)

In [59]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(model.score(X_test,y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

0.875


array([[51,  1],
       [ 9, 19]])

In [ ]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

# from sklearn.tree import DecisionTreeClassifier

# model = DecisionTreeClassifier()
# model.fit(X_train,y_train)
# pred = model.predict(X_test)
# print(model.score(X_test,y_test))
# from sklearn.metrics import confusion_matrix
# confusion_matrix(y_test, pred)

0.825


array([[46,  6],
       [ 8, 20]])