In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Social_Network_Ads_Missing.csv to Social_Network_Ads_Missing.csv


In [3]:
import io
Ads = pd.read_csv(io.BytesIO(uploaded['Social_Network_Ads_Missing.csv']))

In [4]:
# Ads = Ads.dropna()
# Ads.isnull().sum()

In [5]:
X = Ads[["Age","EstimatedSalary"]]
X

Age  EstimatedSalary
0    19.0            19000
1     NaN            20000
2    26.0            43000
3    27.0            57000
4    19.0            76000
..    ...              ...
395  46.0            41000
396  51.0            23000
397  50.0            20000
398  36.0            33000
399  49.0            36000

[400 rows x 2 columns]

In [6]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer()
X = imp.fit_transform(X)
X = pd.DataFrame(X, columns=['Age', 'EstimatedSalary'])
X.isnull().sum()

Age                0
EstimatedSalary    0
dtype: int64

In [7]:
Y = Ads["Purchased"]

In [8]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(model.score(X_test,y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

0.65


array([[52,  0],
       [28,  0]])

In [10]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(model.score(X_test,y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

0.8125


array([[45,  7],
       [ 8, 20]])

In [11]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(model.score(X_test,y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

0.8875


array([[46,  6],
       [ 3, 25]])

In [12]:
pred

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [13]:
X = Ads[["Gender","Age","EstimatedSalary"]]

from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy="most_frequent")
X = imp.fit_transform(X)
# print(X)
X = pd.DataFrame(X)
X
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()
# Xa = X.copy()
X[0] = encoder.fit_transform(X[[0]])

In [14]:
# X.isnull().sum()
X

0   1      2
0    1.0  19  19000
1    1.0  35  20000
2    0.0  26  43000
3    0.0  27  57000
4    1.0  19  76000
..   ...  ..    ...
395  0.0  46  41000
396  1.0  51  23000
397  0.0  50  20000
398  1.0  36  33000
399  0.0  49  36000

[400 rows x 3 columns]

In [15]:
from sklearn.preprocessing import MinMaxScaler
Scaler = MinMaxScaler(feature_range = (0,1))
X = Scaler.fit_transform(X)

In [16]:
X

array([[1.        , 0.02380952, 0.02962963],
       [1.        , 0.4047619 , 0.03703704],
       [0.        , 0.19047619, 0.20740741],
       ...,
       [0.        , 0.76190476, 0.03703704],
       [1.        , 0.42857143, 0.13333333],
       [0.        , 0.73809524, 0.15555556]])

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(model.score(X_test,y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

0.875


array([[51,  1],
       [ 9, 19]])

In [18]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeClassifier


model = DecisionTreeClassifier()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(model.score(X_test,y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)


0.8375


array([[46,  6],
       [ 7, 21]])

In [19]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(model.score(X_test,y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

0.9


array([[47,  5],
       [ 3, 25]])

In [20]:
from sklearn.preprocessing import MinMaxScaler
Scaler = MinMaxScaler(feature_range = (0,1))
X = Scaler.fit_transform(X)

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(model.score(X_test,y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

0.875


array([[51,  1],
       [ 9, 19]])

In [22]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train,y_train)
pred = model.predict(X_test)
print(model.score(X_test,y_test))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

0.825


array([[45,  7],
       [ 7, 21]])