In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv


In [ ]:
import io
Diabetes = pd.read_csv(io.BytesIO(uploaded['diabetes.csv']))

In [ ]:
Diabetes

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [ ]:
X = Diabetes[['Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']]

In [ ]:
Y = Diabetes['Outcome']

In [ ]:
X

Glucose  BloodPressure  SkinThickness  ...   BMI  DiabetesPedigreeFunction  Age
0        148             72             35  ...  33.6                     0.627   50
1         85             66             29  ...  26.6                     0.351   31
2        183             64              0  ...  23.3                     0.672   32
3         89             66             23  ...  28.1                     0.167   21
4        137             40             35  ...  43.1                     2.288   33
..       ...            ...            ...  ...   ...                       ...  ...
763      101             76             48  ...  32.9                     0.171   63
764      122             70             27  ...  36.8                     0.340   27
765      121             72             23  ...  26.2                     0.245   30
766      126             60              0  ...  30.1                     0.349   47
767       93             70             31  ...  30.4                     0.315   23

[768 rows x 7 columns]

In [ ]:
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train,y_train)
pred = model.predict(X_test)

In [ ]:
pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred,labels=[1,0])

array([[36, 19],
       [17, 82]])

In [ ]:
# from sklearn.naive_bayes import GaussianNB

# gnb = GaussianNB()
# gnb.fit(X_train,y_train)
# pred = gnb.predict(X_test)
# confusion_matrix(y_test, pred)

array([[81, 18],
       [19, 36]])